# Generated by Django 4.0.3 on 2022-04-04 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='extraParam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extra_param', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='stage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='singer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('country_code', models.CharField(max_length=50)),
                ('extra_param', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='singer_app.extraparam')),
                ('stage_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='singer_app.stage')),
            ],
        ),
    ]
