# Generated by Django 4.0.3 on 2022-04-04 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('singer_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='singer',
            name='extra_param',
        ),
        migrations.AddField(
            model_name='singer',
            name='extra_param',
            field=models.ManyToManyField(to='singer_app.extraparam'),
        ),
        migrations.RemoveField(
            model_name='singer',
            name='stage_name',
        ),
        migrations.AddField(
            model_name='singer',
            name='stage_name',
            field=models.ManyToManyField(to='singer_app.stage'),
        ),
    ]
